/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabeansshoptable;

import javabeans.model.Product;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanielMoralesGonzale
 */
public class JTableShop extends JPanel {

    private List<Product> productList;

    /**
     * Initialize our table components
     */
    public JTableShop() {
        initComponents();
    }

    /**
     * Load the table data
     */
    public void loadTable() {
        Object[] columnNames = {
            "ID", "CODE", "DESCRIPTION", "COST_PRICE",
            "STOCK", "MIN_STOCK", "CATEGORY"
        };
        // Create table model
        DefaultTableModel modelTable = new DefaultTableModel(new Object[0][0], columnNames);
        if (productList != null) {

            for (int i = 0; i < productList.size(); i++) {
                Object[] obj = new Object[7];
                obj[0] = productList.get(i).getId();
                obj[1] = productList.get(i).getCode();
                obj[2] = productList.get(i).getDescription();
                obj[3] = productList.get(i).getCostPrice();
                obj[4] = productList.get(i).getStock();
                obj[5] = productList.get(i).getMinStock();
                obj[6] = productList.get(i).getCategory();
                modelTable.addRow(obj);
            }

        }
        jTable2 = new JTable(modelTable);
        jScrollPane2.setViewportView(jTable2);

    }

    //Accessors
    public List<Product> getList() {
        return productList;
    }

    public void setList(List<Product> list) {

        this.productList = list;
        if (list != null) {
            loadTable();
        }
        jTable2.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JTableShop().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // End of variables declaration         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
